### ISSUE TITLE
Issue with emoji icons being shifted

### ISSUE THREAD

**Issue by pgedzba** [lentschi/ng-utf8-emojis-to-images#1]
I have added this text: 'Test 😚😇🤔' into my app. After converting it with pipe this is what I got:
![image](https://user-images.githubusercontent.com/26221715/104590629-e6e21e00-566b-11eb-896b-692842415835.png)
This is how it shows in element browser:
![image](https://user-images.githubusercontent.com/26221715/104590665-f1041c80-566b-11eb-85a4-42e12b43732b.png)

Is there something I did wrong? Can I somehow fix this issue?

**Comment by lentschi** [comment]
It's hard to tell without seeing your actual code. But I imagine that you're using a version of `ngx-emoji-mart` that is more recent than the one I used when I wrote `ng-utf8-emojis-to-images` which was `ngx-emoji-mart@3.1.0`.
If so, you should see a matching peer dependency warning on the command line when installing `ng-utf8-emojis-to-images` - am I correct?

To make it work you could either downgrade to `ngx-emoji-mart@3.1.0` or wait until I find the time to upgrade `ng-utf8-emojis-to-images` to make it compatible again.

**Comment by pgedzba** [comment]
Thanks for your fast reply. Downgrading emoji-mart fixed the issue.

**Comment by lentschi** [comment]
> Thanks for your fast reply. Downgrading emoji-mart fixed the issue.

You're welcome! :blush: 

I've looked into this issue and now believe it to be a minor bug (upgrade issue) with `ngx-emoji-mart@4.1.0`, that I've created an [issue](https://github.com/scttcper/ngx-emoji-mart/issues/359) and [PR](https://github.com/scttcper/ngx-emoji-mart/pull/360) for in their repo.

So you can actually still use `ngx-emoji-mart@4.1.0` with `ng-utf8-emojis-to-images` as long as you override the faulty bg image function to provide version 6 of the bg image (see README and StackBlitz on how to do that). Or just wait for this to be fixed in `ngx-emoji-mart`.

I just released `ng-utf8-emojis-to-images@1.2.0` but that version just removes peer dependency warnings and provides correct default parameters for the sample app - so there's no real benefit in updating it.

**Comment by lentschi** [comment]
It has now been fixed in `ngx-emoji-mart@4.1.1`.

**Comment by pgedzba** [comment]
Amazing, thanks a lot!
